#!/bin/bash
ip link set dev eth0 up
ip addr add 192.168.148.1/26 dev eth0
ip link set dev eth1 up
ip addr add 200.6.253.2/27 dev eth1
echo 1 > /proc/sys/net/ipv4/ip_forward
#route add -net 200.6.253.0/27 gw 200.6.253.1
#route add -net 200.6.253.64/26 gw 200.6.253.1
#route add -net 200.6.253.128/26 gw 200.6.253.1
#route add -net 200.6.253.192/26 gw 200.6.253.1
#route add -net 192.168.148.0/26 gw 192.168.148.2
#iptables -p icmp --icmp-type echo-request -d 192.168.148.0/26 -j DROP -A FORWARD

ip route add default via 200.6.253.1

service isc-dhcp-server start

#masquage

iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE

#Filtrage: Refuser tous les traffics
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

#Autorisations

#Ping
iptables -t filter -A OUTPUT -p icmp -j ACCEPT
iptables -t filter -A INPUT -p icmp -j ACCEPT
iptables -t filter -A FORWARD -p icmp -j ACCEPT

#DHCP
iptables -A INPUT -i eth0 -p udp --dport 67:68 --sport 67:68 -j ACCEPT

#DNS
iptables -t filter -A FORWARD -d 200.6.253.195/26 -p udp --dport 53 -j ACCEPT
iptables -t filter -A FORWARD -s 200.6.253.195/26 -p udp --sport 53 -j ACCEPT

# HTTP
#serveur fai
iptables -t filter -A FORWARD -d 200.6.253.194/26 -p tcp --dport 80 -j ACCEPT
iptables -t filter -A FORWARD -s 200.6.253.194/26 -p tcp --sport 80 -j ACCEPT
#serveur privé
iptables -t filter -A FORWARD -d 200.6.253.34/27 -p tcp --dport 80 -j ACCEPT
iptables -t filter -A FORWARD -s 200.6.253.34/27 -p tcp --sport 80 -j ACCEPT
