#!/bin/bash
ip link set dev eth0 up
ip addr add 200.6.253.67/26 dev eth0
ip link set dev eth1 up
ip addr add 200.6.253.131/26 dev eth1
#echo 1 > /proc/sys/net/ipv4/ip_forward
#ip route add default via 200.6.253.65

service quagga start
