#!/bin/bash
ip link set dev eth0 up
ip addr add 200.6.253.129/26 dev eth0
ip link set dev eth1 up
ip addr add 200.6.253.193/26 dev eth1

#echo 1 > /proc/sys/net/ipv4/ip_forward
#route add -net 200.6.253.64/26 gw 200.6.253.131
#route add -net 200.6.253.0/26 gw 200.6.253.131
#route add -net 192.168.148.0/25 gw 200.6.253.131

#routage dynamique
service quagga start


#Filtrage: Refuser tous les traffics
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

#Autorisations 

#ping
iptables -t filter -A OUTPUT -p icmp -j ACCEPT
iptables -t filter -A INPUT -p icmp -j ACCEPT
iptables -t filter -A FORWARD -p icmp -j ACCEPT

# RIP routing
iptables -A INPUT -p udp --dport 520 -j ACCEPT
iptables -A OUTPUT -p udp --dport 520 -j ACCEPT
iptables -A FORWARD -p udp --dport 520 -j ACCEPT

#DNS
iptables -t filter -A FORWARD -d 200.6.253.195/26 -p udp --dport 53 -j ACCEPT
iptables -t filter -A FORWARD -s 200.6.253.195/26 -p udp --sport 53 -j ACCEPT

# HTTP
iptables -t filter -A FORWARD -d 200.6.253.194/26 -p tcp --dport 80 -j ACCEPT
iptables -t filter -A FORWARD -s 200.6.253.194/26 -p tcp --sport 80 -j ACCEPT
