#!/bin/bash
ip link set dev eth0 up
ip addr add 200.6.253.33/27 dev eth0
ip link set dev eth1 up
ip addr add 200.6.253.1/27 dev eth1
ip link set dev eth2 up
ip addr add 200.6.253.65/26 dev eth2
#echo 1 > /proc/sys/net/ipv4/ip_forward
#route add -net 192.168.148.64/26 gw 200.6.253.34
#route add -net 192.168.148.0/26 gw 200.6.253.2
#ip route add default via 200.6.253.66

service quagga start
